feat: adding job module
goto/entropy pull request #74
Opened 2023-09-22 09:03 UTC by lavkesh

2023-09-25 08:42 UTC, ishanarya0 requested changes

2023-09-25 08:42 UTC, ishanarya0 commented on modules/job/driver/driver.go
> +func (driver *Driver) Plan(ctx context.Context, res module.ExpandedResource, act module.ActionRequest) (*resource.Resource, error) {
in the current firehose module structure, we kept Plan , Sync and Output in dedicated files. Let's continue doing this to make the strcuture more predictible?

2023-09-25 08:42 UTC, ishanarya0 commented on modules/job/config/config.go
> +var maxJobNameLength = 47
can you explain how this limit of 47 adds up to 63 name limit?

2023-09-25 08:57 UTC, lavkesh commented on modules/job/driver/driver.go
> +func (driver *Driver) Plan(ctx context.Context, res module.ExpandedResource, act module.ActionRequest) (*resource.Resource, error) {
I think diver package is more readable.

2023-09-25 09:29 UTC, lavkesh commented on modules/job/config/config.go
> +var maxJobNameLength = 47
Considering the pod name length of 63, we should limit the job name. So that it will not cut. Maybe we can return error when the job name is long.

2023-09-26 04:30 UTC, ishanarya0 commented on modules/job/config/config.go
> +var maxJobNameLength = 47
got that but can we allow 53 chars?
53 char for name + "-job" 4 chars + 6 char long hash -> 63 chars

2023-09-26 14:26 UTC, mabdh commented on modules/utils/utils.go
> +package utils
This utils package could go to `/pkg` folder.

Also it is suggested to not having a `util` [package](https://go.dev/blog/package-names) since it is less readable. We can have several packages that serve its function for each.

2023-09-26 14:28 UTC, mabdh commented on modules/firehose/driver.go
> -	var tolerations = []map[string]any{}
it is okay to have `var` here actually.

2023-09-26 14:31 UTC, mabdh commented on core/core.go
> -	logger         *zap.Logger
Logging changes should ideally go to other PR. Making the PR as easy as possible to read would make it faster for reviewer to check.

2023-09-26 14:32 UTC, mabdh commented on modules/job/config/config.go
> +	Namespace         string                       `json:"namespace"`         // maybe we shouldn't restrict namespace?
IMO we should make the namespace as a mandatory one for better readability.

2023-09-26 14:33 UTC, mabdh commented on modules/job/config/config.go
> +type ConfigMap struct {
```suggestion
}

type ConfigMap struct {
```

2023-09-26 14:35 UTC, mabdh commented on modules/job/config/config.go
> +	rl := dc.RequestsAndLimits["default"]
This `default` key is indeed always exist since we are doing validation. But can we make this more guarded by checking whether `rl` exist or not, if not throws error? otherwise, it will throw panic later.

2023-09-26 14:56 UTC, mabdh commented on modules/job/driver/driver.go
> +			return nil, errors.ErrInternal.WithMsgf("unknown step:")
```suggestion
			return nil, errors.ErrInternal.WithMsgf("unknown step: '%s'", pendingStep)
```

2023-09-26 14:56 UTC, mabdh commented on modules/job/driver/models.go
> +	Create PendingStep = iota
using `iota` here would make it assigned as integer right? can we just use string for better readability?

2023-09-26 14:56 UTC, mabdh commented on modules/job/driver/models.go
> +package driver
also, can we not have a `model` file? it is also similar with how could we name a package better. We can still follow other modules, put Output in `output.go`, etc.

2023-09-26 14:56 UTC, mabdh commented on modules/job/driver/models.go
> +type Output struct {
This could be going to `output.go`

2023-09-26 14:56 UTC, mabdh commented on modules/job/driver/sync.go
> +	job2 "github.com/goto/entropy/modules/job/config"
rather than `job2`, calling it `jobmodule` would be more intutitive IMO

2023-09-26 14:56 UTC, mabdh commented on modules/job/driver/sync.go
> +		if v.Kind == "config-map" {
can we make the `kind` similar with k8s API as `configMap` ?
https://github.com/kubernetes/api/blob/master/core/v1/types.go#L131

2023-09-26 14:56 UTC, mabdh commented on pkg/kube/client.go
> +	return job, err
just do this maybe

```suggestion
	return job, waitForJob(ctx, name, jobs)
```

2023-09-26 14:56 UTC, mabdh commented on pkg/kube/job/processor.go
> +	Invalid StatusType = iota
again if it is not really necessary to use `iota`, I think we just could use string for better readability.

2023-09-26 15:06 UTC, spy16 commented on modules/job/driver/sync.go
> +	job2 "github.com/goto/entropy/modules/job/config"
or `jobconfig`

2023-09-27 03:55 UTC, mabdh commented on modules/job/driver/sync.go
> +	job2 "github.com/goto/entropy/modules/job/config"
oh yes `jobconfig` is even better

2023-09-27 06:00 UTC, lavkesh commented on modules/utils/utils.go
> +package utils
hm. alright! let's remove utils package

2023-09-27 06:01 UTC, lavkesh commented on core/core.go
> -	logger         *zap.Logger
let me remove the logging changes separately.

2023-09-27 06:02 UTC, lavkesh commented on modules/firehose/driver.go
> -	var tolerations = []map[string]any{}
yea.notsure why this is changed..

2023-09-27 08:10 UTC, lavkesh commented on modules/job/driver/sync.go
> +	job2 "github.com/goto/entropy/modules/job/config"
yea seems like autocomplete. will fix thisl

2023-09-27 08:14 UTC, lavkesh commented on modules/job/driver/models.go
> +	Create PendingStep = iota
hm. i like to use enum idioms in golang.. 
maybe if we really need string representation then we can use 
something like 
https://pkg.go.dev/golang.org/x/tools/cmd/stringer

2023-09-27 08:15 UTC, lavkesh commented on modules/job/driver/models.go
> +	Create PendingStep = iota
we can use //go:generate stringer -type=PendingStep

2023-09-28 08:13 UTC, lavkesh commented on modules/utils/utils.go
> +package utils
I will keep in module package, and remove the utils folder. @mabdh

2023-09-28 09:56 UTC, lavkesh commented on modules/job/driver/models.go
> +	Create PendingStep = iota
for this one we should use string, because it's persistent. fixedit.

2023-09-28 09:56 UTC, lavkesh commented on pkg/kube/job/processor.go
> +	Invalid StatusType = iota
I think this one is fine, it's only used internal.

2023-09-28 10:08 UTC, lavkesh commented on modules/job/config/config.go
> +var maxJobNameLength = 47
alright! let me fix this:)

2023-09-28 10:14 UTC, lavkesh commented on modules/job/config/config.go
> +	Namespace         string                       `json:"namespace"`         // maybe we shouldn't restrict namespace?
will add the config.go validation.. these can be done later point of time too..

2023-09-28 10:25 UTC, lavkesh commented on modules/job/config/config.go
> +	rl := dc.RequestsAndLimits["default"]
hmm. we can make it more readable. if rl is empty struct, the resources will be empty string which is fine.

2023-09-29 03:11 UTC, mabdh commented
@lavkesh try changing golang-ci lint to version `v1.54.2` in the workflow

2023-09-29 10:23 UTC, mabdh approved these changes

2023-09-29 10:26 UTC, ishanarya0 approved these changes

2023-09-29 10:26 UTC, merged